// The game's sprites: sheets of equally sized frames, by name. Frames are named so the game can refer to them.
import { pixels } from '../lib/pixelArt.mjs';

const Cat = {
    // facing down, toward the player.
    down: pixels(`
        ................
        ...k........k...
        ..kpk......kpk..
        ..kppkkkkkkppk..
        ..kooooOOooook..
        .kooooOooOooook.
        .koowkoooowkook.
        .kookkooookkook.
        .kooooowwoooook.
        ..koowwppwwook..
        ...kowkwwkwok...
        ...kkooooookk...
        ..koOooooooOok..
        ..kowwoooowwok..
        ...kkkkkkkkkk...
        ................`),
    // facing down, blinking.
    blink: pixels(`
        ................
        ...k........k...
        ..kpk......kpk..
        ..kppkkkkkkppk..
        ..kooooOOooook..
        .kooooOooOooook.
        .kooooooooooook.
        .kookkooookkook.
        .kooooowwoooook.
        ..koowwppwwook..
        ...kowkwwkwok...
        ...kkooooookk...
        ..koOooooooOok..
        ..kowwoooowwok..
        ...kkkkkkkkkk...
        ................`),
    // facing up, away from the player: the back of its head and its tail.
    up: pixels(`
        ................
        ...k........k...
        ..kok......kok..
        ..kookkkkkkook..
        ..kooooOOooook..
        .kooOooOOooOook.
        .koooooOOoooook.
        .kooOooooooOook.
        ..koooooooooook.
        ...kkoooooookk..
        ..koOooooooOok..
        ..kooOooooOook..
        ..koooookooook..
        ...kkkkokkkkk...
        ......kok.......
        .......k........`),
    // facing right, in profile. Drawn flipped for facing left.
    side: pixels(`
        ................
        .........k...k..
        ........kpk.kpk.
        .k......koooook.
        kok....kooOooook
        kok....koooookok
        kok....kooooooop
        .kok...koooowwwk
        ..kokkkkkkkkkkk.
        ..kooOooooOoook.
        ..koOooooOooook.
        ..koooooooooook.
        ..kwwooooooowwk.
        ...kkkkkkkkkkk..
        ................
        ................`),
    // flattened by a car.
    squashed: pixels(`
        ................
        ................
        ................
        ................
        ................
        ................
        ................
        ..k..........k..
        .kpk........kpk.
        .kookkkkkkkkook.
        kooOokooookoOook
        kooooooooooooook
        .kooOooooooOook.
        ..kkkkkkkkkkkk..
        ................
        ................`),
    // one of its lives floating away.
    ghost1: pixels(`
        ................
        ...k........k...
        ..kwk......kwk..
        ..kwwkkkkkkwwk..
        ..kwwwwwwwwwwk..
        .kwwwwwwwwwwwwk.
        .kwwkkwwwwkkwwk.
        .kwwwwwwwwwwwwk.
        .kwwwwwppwwwwwk.
        ..kwwwwwwwwwwk..
        ..kwwwwwwwwwwk..
        ..kwwwwwwwwwwk..
        ..kwwwwwwwwwwk..
        ..kwkwwkkwwkwk..
        ...k.kk..kk.k...
        ................`),
    ghost2: pixels(`
        ................
        ...k........k...
        ..kwk......kwk..
        ..kwwkkkkkkwwk..
        ..kwwwwwwwwwwk..
        .kwwwwwwwwwwwwk.
        .kwwkkwwwwkkwwk.
        .kwwwwwwwwwwwwk.
        .kwwwwwppwwwwwk.
        ..kwwwwwwwwwwk..
        ..kwwwwwwwwwwk..
        ..kwwwwwwwwwwk..
        ..kwwkwwwwkwwk..
        ..kkwkkwwkkwkk..
        ....k..kk..k....
        ................`),
};

// facing right, a template for each color: X is the body and Z its shade.
const Car = [
    '................................',
    '....kkkk..............kkkk......',
    '..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..',
    '.kXXXXXXXXXXXXXXXXXXXXXXXXXXXXk.',
    '.krXXXXkcckZZZZZZZZZkccckXXXXyk.',
    '.kXXXXXkcckZZZZZZZZZkccckXXXXXk.',
    '.kXXXXXkcckZZZZZZZZZkccckXXXXXk.',
    '.kXXXXXkcckZZZZZZZZZkccckXXXXXk.',
    '.kXXXXXkcckZZZZZZZZZkccckXXXXXk.',
    '.kXXXXXkcckZZZZZZZZZkccckXXXXXk.',
    '.kXXXXXkcckZZZZZZZZZkccckXXXXXk.',
    '.krXXXXkcckZZZZZZZZZkccckXXXXyk.',
    '.kZZZZZZZZZZZZZZZZZZZZZZZZZZZZk.',
    '..kkkkkkkkkkkkkkkkkkkkkkkkkkkk..',
    '....kkkk..............kkkk......',
    '................................',
];

function paintCar(body, shade) {
    return Car.map(row => row.replaceAll('X', body).replaceAll('Z', shade));
}

const Vehicles = {
    sprCar: { width: 32, height: 16, frames: { red: paintCar('r', 'R'), blue: paintCar('b', 'B'), yellow: paintCar('y', 'Y'), green: paintCar('e', 'E') } },
    // a mail truck, facing right.
    sprTruck: { width: 48, height: 16, frames: {
        truck: pixels(`
            ................................................
            ....kkkk..............kkkk............kkkk......
            .kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.kkkkkkkkkkkk.
            .kwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwk.kbbbbbbbbbyk.
            .kwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwk.kbbbbbbbbbbk.
            .kwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwk.kbbbkcccckbk.
            .kbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbkkkbbbkcccckbk.
            .kbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbkkkbbbkcccckbk.
            .kwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwkkkbbbkcccckbk.
            .kwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwkkkbbbkcccckbk.
            .kwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwk.kbbbkcccckbk.
            .kwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwk.kbbbbbbbbbbk.
            .kgggggggggggggggggggggggggggggggk.kBBBBBBBBByk.
            .kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.kkkkkkkkkkkk.
            ....kkkk..............kkkk............kkkk......
            ................................................`),
    } },
    // a cyclist, facing right.
    sprBike: { width: 16, height: 16, frames: {
        bike: pixels(`
            ................
            ................
            ................
            .....kkkk.......
            ....kbbbbk......
            ....kbNNbkkkg...
            ....kbNNNbk.g...
            kkkkbNNNbkggkkkk
            kkkkbNNNbkggkkkk
            ....kbNNNbk.g...
            ....kbNNbkkkg...
            ....kbbbbk......
            .....kkkk.......
            ................
            ................
            ................`),
    } },
};

const Floaters = {
    sprCrate: { width: 16, height: 16, frames: {
        crate: pixels(`
            ................
            .kkkkkkkkkkkkkk.
            .kNNNNNNNNNNNNk.
            .kNnnnnnnnnnnNk.
            .kNnnnnTnnnnnNk.
            .kNNNNNNNNNNNNk.
            .kNnnnnnnnnnnNk.
            .kNnnnnnnnTnnNk.
            .kNNNNNNNNNNNNk.
            .kNnnnnnnnnnnNk.
            .kNnnTnnnnnnnNk.
            .kNNNNNNNNNNNNk.
            .kNnnnnnnnnnnNk.
            .kNnnnnnnnnnnNk.
            .kNNNNNNNNNNNNk.
            .kkkkkkkkkkkkkk.`),
    } },
    // facing left: swimming, diving tail up, and under water.
    sprDuck: { width: 16, height: 16, frames: {
        swim1: pixels(`
            ................
            ................
            ................
            ...kkkk.........
            ..kwwwwk........
            ookwkwwkkkkkk...
            oowwwwwwwwwwwwk.
            .kwwwwwwwwwwwgk.
            ..kwwwkwwwggwgk.
            ..kwwwwkwwwwwgk.
            ...kwwwkwwwwwk..
            ....kkkkkkkkkkk.
            ................
            .cc.....ccc.....
            ................
            ................`),
        swim2: pixels(`
            ................
            ................
            ................
            ...kkkk.........
            ..kwwwwk........
            ookwkwwkkkkkk...
            oowwwwwwwwwwwwk.
            .kwwwwwwwwwwwgk.
            ..kwwwkwwwggwgk.
            ..kwwwwkwwwwwgk.
            ...kwwwkwwwwwk..
            ....kkkkkkkkkkk.
            ................
            ...cc.....ccc...
            ................
            ................`),
        dive: pixels(`
            ................
            ................
            ................
            ................
            ................
            ................
            ......kkk.......
            .....kwwwk......
            .....kwwwk......
            ....kwwwwwk.....
            ...ckwwwwwkc....
            ..cc.kkkkk.cc...
            ................
            ...cc....cc.....
            ................
            ................`),
        under: pixels(`
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            ......ccc.......
            ....c.....c.....
            ...c.......c....
            ....c.....c.....
            ......ccc.......
            ................
            ................
            ................`),
    } },
};

const Goal = {
    // the boxes on the roof: empty, and with a cat asleep in it.
    sprBox: { width: 16, height: 16, frames: {
        empty: pixels(`
            ................
            ................
            ................
            .kkkkkkkkkkkkkk.
            .kTkkkkkkkkkkTk.
            .kTkkkkkkkkkkTk.
            .kTDDDDDDDDDDTk.
            .kTTTTTTTTTTTTk.
            .kttttttttttttk.
            .ktttttTTtttttk.
            .ktttttTTtttttk.
            .kttttttttttttk.
            .kTTTTTTTTTTTTk.
            .kkkkkkkkkkkkkk.
            ................
            ................`),
        cat: pixels(`
            ................
            ...k....k.......
            ..kok..kok......
            .kkooooookkkkkk.
            .kkkkookkkkkkTk.
            .kkooppookDDDTk.
            .kTkkkkkkkDDDTk.
            .kTTTTTTTTTTTTk.
            .kttttttttttttk.
            .ktttttTTtttttk.
            .ktttttTTtttttk.
            .kttttttttttttk.
            .kTTTTTTTTTTTTk.
            .kkkkkkkkkkkkkk.
            ................
            ................`),
    } },
    sprSplash: { width: 16, height: 16, frames: {
        splash1: pixels(`
            ................
            ................
            ................
            ................
            .......cc.......
            ....c..cc..c....
            ...c...ww...c...
            .....cwwwwc.....
            ....cwbbbbwc....
            ...cwbbbbbbwc...
            ....ccwwwwcc....
            ......cccc......
            ................
            ................
            ................
            ................`),
        splash2: pixels(`
            ................
            ................
            ................
            ..c..........c..
            ....c......c....
            .......ww.......
            ..c...wwww...c..
            ................
            ...cc......cc...
            ..cwwbbbbbbwwc..
            ...ccwwwwwwcc...
            .....cccccc.....
            ................
            ................
            ................
            ................`),
        splash3: pixels(`
            ................
            ................
            ................
            ................
            ................
            ................
            ................
            .....cccccc.....
            ...cc......cc...
            ..c............c
            ...cc......cc...
            .....cccccc.....
            ................
            ................
            ................
            ................`),
    } },
};

const Railway = {
    // a train, facing right: the engine, and the cars behind it.
    sprTrain: { width: 32, height: 16, frames: {
        engine: pixels(`
            ................................
            .kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.
            .kRRRRRRRRRRRRRRRRRRRRRRRRRRRRk.
            .kggggggggggggggggggggggggggggk.
            .kgggGGGGggggggggGGGGgggggcccyk.
            .kgggGGGGggggggggGGGGgggggcccgk.
            .kgggGGGGggggggggGGGGgggggcccgk.
            kkgggGGGGggggggggGGGGgggggcccgk.
            kkgggGGGGggggggggGGGGgggggcccgk.
            .kgggGGGGggggggggGGGGgggggcccgk.
            .kgggGGGGggggggggGGGGgggggcccgk.
            .kgggGGGGggggggggGGGGgggggcccyk.
            .kggggggggggggggggggggggggggggk.
            .kRRRRRRRRRRRRRRRRRRRRRRRRRRRRk.
            .kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.
            ................................`),
        car: pixels(`
            ................................
            .kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.
            .kRRRRRRRRRRRRRRRRRRRRRRRRRRRRk.
            .kggggggggggggggggggggggggggggk.
            .kgggGGGGggggggggGGGGgggggggggk.
            .kgggGGGGggggggggGGGGgggggggggk.
            .kgggGGGGggggggggGGGGgggggggggk.
            kkgggGGGGggggggggGGGGgggggggggkk
            kkgggGGGGggggggggGGGGgggggggggkk
            .kgggGGGGggggggggGGGGgggggggggk.
            .kgggGGGGggggggggGGGGgggggggggk.
            .kgggGGGGggggggggGGGGgggggggggk.
            .kggggggggggggggggggggggggggggk.
            .kRRRRRRRRRRRRRRRRRRRRRRRRRRRRk.
            .kkkkkkkkkkkkkkkkkkkkkkkkkkkkkk.
            ................................`),
    } },
    // the lights at a railroad crossing: off, and flashing one side then the other.
    sprSignal: { width: 16, height: 16, frames: {
        off: pixels(`
            ................
            ...kkkk..kkkk...
            ...kkkk..kkkk...
            ...kkkk..kkkk...
            ...kkkkkkkkkk...
            ....w......w....
            .....w.GG.w.....
            ......wGGw......
            .......ww.......
            ......wGGw......
            .....w.GG.w.....
            ....w..GG..w....
            .......GG.......
            .......GG.......
            .....kkkkkk.....
            ................`),
        left: pixels(`
            ................
            ...kkkk..kkkk...
            ...krrk..kkkk...
            ...krrk..kkkk...
            ...kkkkkkkkkk...
            ....w......w....
            .....w.GG.w.....
            ......wGGw......
            .......ww.......
            ......wGGw......
            .....w.GG.w.....
            ....w..GG..w....
            .......GG.......
            .......GG.......
            .....kkkkkk.....
            ................`),
        right: pixels(`
            ................
            ...kkkk..kkkk...
            ...kkkk..krrk...
            ...kkkk..krrk...
            ...kkkkkkkkkk...
            ....w......w....
            .....w.GG.w.....
            ......wGGw......
            .......ww.......
            ......wGGw......
            .....w.GG.w.....
            ....w..GG..w....
            .......GG.......
            .......GG.......
            .....kkkkkk.....
            ................`),
    } },
};

const Bonus = {
    // now and then, in an empty box.
    sprFish: { width: 16, height: 16, frames: {
        fish: pixels(`
            ................
            ................
            ................
            ................
            .....kkkkk......
            ...kkbbbbbk..kk.
            ..kwkbbbbbkkbbk.
            .kbbcccccckkbbk.
            .kbbcccccckkbbk.
            ..kbbbbbbbkkbbk.
            ...kkbbbbbk..kk.
            .....kkkkk......
            ................
            ................
            ................
            ................`),
    } },
};

const Effects = {
    // a twinkling star, bursting from a box when a cat gets home.
    sprSparkle: { width: 8, height: 8, frames: {
        big: pixels(`
            ...y....
            ...y....
            ..yyy...
            yyywyyy.
            ..yyy...
            ...y....
            ...y....
            ........`),
        small: pixels(`
            ........
            ........
            ...y....
            ..ywy...
            ...y....
            ........
            ........
            ........`),
    } },
};

export const Sprites = {
    sprCat: { width: 16, height: 16, frames: Cat },
    ...Vehicles,
    ...Floaters,
    ...Goal,
    ...Railway,
    ...Bonus,
    ...Effects,
};
