// Draws the game's images from the pixel art in tools/art/, into game/resources/. Run with: npm run art
//   --preview <folder>  also saves each image scaled up 4x there, for a closer look.
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { FontCellSize, FontCharacters, Glyphs } from './art/font.mjs';
import { Palette } from './art/palette.mjs';
import { Sprites } from './art/sprites.mjs';
import { Tiles, TileSize } from './art/tiles.mjs';
import { Image, sheet } from './lib/pixelArt.mjs';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const resources = join(root, 'game', 'resources');

const previewIndex = process.argv.indexOf('--preview');
const previewFolder = previewIndex >= 0 ? process.argv[previewIndex + 1] : undefined;

// The image scaled up, on a checkerboard where it's transparent.
function preview(image, scale) {
    const result = new Image(image.width * scale, image.height * scale);
    for (let y = 0; y < result.height; y++) {
        for (let x = 0; x < result.width; x++) {
            const source = (Math.floor(y / scale) * image.width + Math.floor(x / scale)) * 4;
            const checker = (Math.floor(x / 8) + Math.floor(y / 8)) % 2 ? [48, 48, 64, 255] : [64, 64, 84, 255];
            const pixel = image.data[source + 3] > 0 ? image.data.subarray(source, source + 4) : checker;
            result.data.set(pixel, (y * result.width + x) * 4);
        }
    }
    return result;
}

function save(image, name) {
    image.save(join(resources, name));
    if (previewFolder) {
        preview(image, 4).save(join(previewFolder, name));
    }
    console.log(`${name}: ${image.width}x${image.height}`);
}

// Values the game needs to read the images, as a TypeScript module.
function saveModule(values) {
    const path = join(root, 'game', 'generated', 'art.ts');
    const lines = Object.entries(values).map(([name, value]) => `export const ${name} = ${JSON.stringify(value)};`);
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, `// Generated by tools/build-art.mjs (npm run art). Don't edit.\n${lines.join('\n')}\n`);
}

const missingGlyphs = Array.from(FontCharacters).filter(character => !Glyphs[character]);
if (missingGlyphs.length > 0) {
    throw new Error(`The font has no glyphs for: ${missingGlyphs.join(' ')}`);
}

save(sheet(Array.from(FontCharacters).map(character => Glyphs[character]), FontCellSize, FontCellSize, 16, Palette), 'font.png');

// each sprite's size and the index of each of its frames, by name.
const spriteFrames = {};
for (const [name, sprite] of Object.entries(Sprites)) {
    const frameNames = Object.keys(sprite.frames);
    const columns = Math.max(1, Math.floor(256 / sprite.width));
    save(sheet(Object.values(sprite.frames), sprite.width, sprite.height, columns, Palette, true), `sprites/${name}.png`);
    spriteFrames[name] = { width: sprite.width, height: sprite.height, frames: Object.fromEntries(frameNames.map((frame, index) => [frame, index])) };
}

// the tileset, with a Tiled tileset (.tsx) describing it.
const tileNames = Object.keys(Tiles);
const tileColumns = 8;
const tileset = sheet(Object.values(Tiles), TileSize, TileSize, tileColumns, Palette, true);
save(tileset, 'maps/tiles.png');
writeFileSync(join(resources, 'maps', 'tiles.tsx'), [
    '<?xml version="1.0" encoding="UTF-8"?>',
    `<tileset version="1.10" tiledversion="1.11.0" name="tiles" tilewidth="${TileSize}" tileheight="${TileSize}" tilecount="${tileNames.length}" columns="${tileColumns}">`,
    ` <image source="tiles.png" width="${tileset.width}" height="${tileset.height}"/>`,
    ...tileNames.map((name, id) => ` <tile id="${id}" type="${name}"/>`),
    '</tileset>',
    '',
].join('\n'));

saveModule({
    FontCharacters: FontCharacters,
    FontCellSize: FontCellSize,
    Sprites: spriteFrames,
    TileSize: TileSize,
    // each tile's id in the tileset, by name.
    Tiles: Object.fromEntries(tileNames.map((name, id) => [name, id])),
});
