// Synthesizes the game's sound effects from tools/sounds/effects.mjs, into game/resources/sounds/. Run with: npm run sfx
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { render, SampleRate, saveWav } from './lib/synth.mjs';
import { Effects } from './sounds/effects.mjs';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const sounds = join(root, 'game', 'resources', 'sounds');

for (const [name, voices] of Object.entries(Effects)) {
    const samples = render(voices);
    saveWav(join(sounds, `${name}.wav`), samples);
    console.log(`${name}.wav: ${(samples.length / SampleRate).toFixed(2)}s`);
}

// the names of the sounds, for the game to load them.
writeFileSync(join(root, 'game', 'generated', 'sounds.ts'), `// Generated by tools/build-sfx.mjs (npm run sfx). Don't edit.\nexport const SoundNames = ${JSON.stringify(Object.keys(Effects))};\n`);
